# workload.properties — read50/update50 with Zipfian(0.99)
recordcount=2000000
operationcount=2000000
# Operation mix
readproportion=1
updateproportion=0
insertproportion=0
scanproportion=0
readmodifywriteproportion=0

# Request distribution (key popularity)
requestdistribution=zipfian
zipfianconstant=0.99

# Record/field settings (adjust as needed)
fieldcount=1
fieldlength=2

# Read/modify details
readallfields=true
writeallfields=true

workload=site.ycsb.workloads.CoreWorkload